blog/urls.py
from django.urls import path
from . import views

app_name='blog'
urlpatterns= [
    path('',views.blogPost, name='blogPost'),
    path('inputComment',views.inputComment,name='inputComment')
]

blogWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

class BlogPost(models.Model):
    article_title = models.CharField(max_length=200)
    article_text = models.TextField(max_length=5000)
    article_author = models.CharField(max_length=100)

class Comment(models.Model):
    comment_author = models.CharField(max_length=100, default="anonymous")
    comment_text = models.CharField(max_length=1000)

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import BlogPost, Comment
from django.urls import reverse

def blogPost(request):
    blog = BlogPost.objects.all()[0]
    comments = reversed(Comment.objects.all())
    return render(request, 'blog/blogPost.html', {"blog_post":blog, "comments":comments})
# Create your views here.

def inputComment(request):
    if(request.POST.get('commentText')==False or request.POST.get('commentText').strip()==""):
        return HttpResponseRedirect(reverse('blog:blogPost', args=()))
    else:
        if(request.POST.get('commentAuthor','anonymous')==""):
            newComment = Comment(comment_author='anonymous',comment_text=request.POST["commentText"])
        else:
            newComment = Comment(comment_author=request.POST.get('commentAuthor','anonymous'),comment_text=request.POST["commentText"])
        newComment.save()
        return HttpResponseRedirect(reverse('blog:blogPost', args=()))

        

blog/templates/blog/base.html
<html>
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
<head>
    <title>
    My Blog Website
    </title>
</head>
<body class= "bg-light">
    <header>
        <nav class="navbar navbar-dark bg-dark fixed-top">
            <a class="navbar-brand mx-3" href="{% url 'blog:blogPost' %}"> My Blog Website </a>
        </nav>
    </header>
    <div id="content" name="content" class="mt-5">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

blog/templates/blog/blogPost.html
{% extends 'blog/base.html' %}
{% block content %}
<main role="main" class="container">
<div class= "my-3 p-3 bg-white rounded box-shadow">
    <h1 class="border-bottom border-gray pb-2 mb-2">{{blog_post.article_title}}</h1>
    <strong class="d-block text-gray-dark">By {{blog_post.article_author}}</strong>
    <p>{{blog_post.article_text | linebreaks}}</p>
</div>

<div class= "my-3 p-3 bg-white rounded box-shadow">
    <h2 class="border-bottom border-gray pb-2 mb-0">Comments</h2>
    <form action="{% url 'blog:inputComment' %}" method="POST">
        {% csrf_token %}
            <div class="form-group">
                <input type="text" id="commentAuthor" class="form-control form-control-sm" name="commentAuthor" placeholder="Name (optional)" />
            </div>
        <div class="form-group">
            <textarea class = "form-control" id="commentText" rows="2" name="commentText" placeholder="Comment"> </textarea>
        </div>
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>

    {% for comment in comments %}
    <div class="media text text-muted pt-3">
        <p class="media-body pb-3 mb-0 small 1h-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">{{comment.comment_author}}</strong>
            {{comment.comment_text}}
        </p>
    {% endfor %}
</div>
</main>
{% endblock %}